name: coldstartcpi
channels:
  - bioconda
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.8
  - rdkit-pypi=2022.9.4
  - numpy=1.18.1
  - mol2vec
  - bio-embeddings
  - scikit-learn=1.0.2
  - pandas=1.0.1
  - tqdm
  - prefetch-generator
  - pytorch::pytorch-cuda=10.2 # 11.3 and 11.6 is OK
  - pytorch::pytorch=1.12.0
